# Form implementation generated from reading ui file 'secondProject.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1174, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.leftFream = QtWidgets.QFrame(Form)
        self.leftFream.setGeometry(QtCore.QRect(10, 10, 80, 715))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFream.sizePolicy().hasHeightForWidth())
        self.leftFream.setSizePolicy(sizePolicy)
        self.leftFream.setStyleSheet("background-color: rgb(0, 24, 102);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.leftFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFream.setObjectName("leftFream")
        self.headLable = QtWidgets.QLabel(self.leftFream)
        self.headLable.setGeometry(QtCore.QRect(0, 40, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headLable.sizePolicy().hasHeightForWidth())
        self.headLable.setSizePolicy(sizePolicy)
        self.headLable.setText("")
        self.headLable.setObjectName("headLable")
        self.leftButton1 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton1.setGeometry(QtCore.QRect(0, 240, 80, 40))
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton1.setObjectName("leftButton1")
        self.leftButton2 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton2.setGeometry(QtCore.QRect(0, 280, 80, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton2.sizePolicy().hasHeightForWidth())
        self.leftButton2.setSizePolicy(sizePolicy)
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton2.setObjectName("leftButton2")
        self.leftButton3 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton3.setGeometry(QtCore.QRect(0, 320, 80, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton3.sizePolicy().hasHeightForWidth())
        self.leftButton3.setSizePolicy(sizePolicy)
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton3.setObjectName("leftButton3")
        self.topFream = QtWidgets.QFrame(Form)
        self.topFream.setGeometry(QtCore.QRect(90, 10, 1074, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFream.sizePolicy().hasHeightForWidth())
        self.topFream.setSizePolicy(sizePolicy)
        self.topFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:10px;\n"
"")
        self.topFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topFream.setObjectName("topFream")
        self.lineButton = QtWidgets.QPushButton(self.topFream)
        self.lineButton.setGeometry(QtCore.QRect(984, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineButton.sizePolicy().hasHeightForWidth())
        self.lineButton.setSizePolicy(sizePolicy)
        self.lineButton.setText("")
        self.lineButton.setObjectName("lineButton")
        self.closeButton = QtWidgets.QPushButton(self.topFream)
        self.closeButton.setGeometry(QtCore.QRect(1024, 0, 40, 40))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.closeButton.raise_()
        self.lineButton.raise_()
        self.midFream = QtWidgets.QFrame(Form)
        self.midFream.setGeometry(QtCore.QRect(90, 50, 1074, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midFream.sizePolicy().hasHeightForWidth())
        self.midFream.setSizePolicy(sizePolicy)
        self.midFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.midFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.midFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.midFream.setObjectName("midFream")
        self.midlabel = QtWidgets.QLabel(self.midFream)
        self.midlabel.setGeometry(QtCore.QRect(50, 20, 181, 41))
        self.midlabel.setStyleSheet("font: 700 25pt \"微软雅黑\";")
        self.midlabel.setObjectName("midlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.midFream)
        self.lineEdit.setGeometry(QtCore.QRect(750, 30, 300, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"font: 15pt \"微软雅黑\";\n"
"border:2px;\n"
"border-color: rgb(0,24,102);\n"
"border-radius:20px;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.screenButton = QtWidgets.QPushButton(self.midFream)
        self.screenButton.setGeometry(QtCore.QRect(510, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenButton.sizePolicy().hasHeightForWidth())
        self.screenButton.setSizePolicy(sizePolicy)
        self.screenButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.screenButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"selection-background-color: rgb(231,244,255);")
        self.screenButton.setText("")
        self.screenButton.setObjectName("screenButton")
        self.label = QtWidgets.QLabel(self.midFream)
        self.label.setGeometry(QtCore.QRect(570, 40, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("\n"
"font: 15pt \"幼圆\";")
        self.label.setObjectName("label")
        self.midlabel.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.screenButton.raise_()
        self.mainFream = QtWidgets.QFrame(Form)
        self.mainFream.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFream.sizePolicy().hasHeightForWidth())
        self.mainFream.setSizePolicy(sizePolicy)
        self.mainFream.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"\n"
"border-bottom-right-radius:10px;")
        self.mainFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream.setObjectName("mainFream")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leftButton1.setText(_translate("Form", "个人信息"))
        self.leftButton2.setText(_translate("Form", "课表信息"))
        self.leftButton3.setText(_translate("Form", "成绩信息"))
        self.midlabel.setText(_translate("Form", "欢迎使用"))
        self.label.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
