# Form implementation generated from reading ui file '_standardMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import datetime

import xlwt
from PyQt6 import QtCore, QtWidgets, QtSql
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QCursor, QPixmap, QIcon, QColor
from PyQt6.QtSql import QSqlQuery, QSqlTableModel
from PyQt6.QtWidgets import QGraphicsDropShadowEffect
from PyQt6.QtWidgets  import QAbstractItemView

from student import item_delegate


class teaMain(QtWidgets.QMainWindow):
    def __init__(self,id=105000):
        super(teaMain, self).__init__()
        self.id = id
        db = QtSql.QSqlDatabase.addDatabase('QMYSQL')
        q = "soft"
        db.setDatabaseName(q)
        db.setUserName('root')
        db.setPassword('root')
        db.setPort(3306)
        db.open()
        self.db = db
        self.model = QSqlTableModel()
        self.setupUi()
        self.slot_leftButton1()
        self.show()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1174, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        # 设置窗口无边框和阴影
        self.setWindowFlag(Qt.WindowType.FramelessWindowHint)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        effect = QGraphicsDropShadowEffect()
        effect.setOffset(4, 4)
        effect.setColor(QColor(0, 0, 0, 50))
        effect.setBlurRadius(10)
        self.setGraphicsEffect(effect)

        self.leftFream = QtWidgets.QFrame(self)
        self.leftFream.setGeometry(QtCore.QRect(10, 10, 80, 715))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFream.sizePolicy().hasHeightForWidth())
        self.leftFream.setSizePolicy(sizePolicy)
        self.leftFream.setStyleSheet("background-color: rgb(0, 24, 102);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.leftFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFream.setObjectName("leftFream")
        self.headLable = QtWidgets.QLabel(self.leftFream)
        self.headLable.setGeometry(QtCore.QRect(0, 40, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headLable.sizePolicy().hasHeightForWidth())
        self.headLable.setSizePolicy(sizePolicy)
        self.headLable.setText("")
        self.headLable.setObjectName("headLable")
        self.leftButton2 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton2.setGeometry(QtCore.QRect(0, 270, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton2.sizePolicy().hasHeightForWidth())
        self.leftButton2.setSizePolicy(sizePolicy)
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton2.setObjectName("leftButton2")
        self.leftButton4 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton4.setGeometry(QtCore.QRect(0, 390, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton4.sizePolicy().hasHeightForWidth())
        self.leftButton4.setSizePolicy(sizePolicy)
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton4.setObjectName("leftButton4")
        self.leftButton1 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton1.setGeometry(QtCore.QRect(0, 210, 80, 60))
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton1.setObjectName("leftButton1")
        self.leftButton3 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton3.setGeometry(QtCore.QRect(0, 330, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton3.sizePolicy().hasHeightForWidth())
        self.leftButton3.setSizePolicy(sizePolicy)
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton3.setObjectName("leftButton3")
        self.topFream = QtWidgets.QFrame(self)
        self.topFream.setGeometry(QtCore.QRect(90, 10, 1074, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFream.sizePolicy().hasHeightForWidth())
        self.topFream.setSizePolicy(sizePolicy)
        self.topFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:10px;\n"
"")
        self.topFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topFream.setObjectName("topFream")
        self.lineButton = QtWidgets.QPushButton(self.topFream)
        self.lineButton.setGeometry(QtCore.QRect(984, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineButton.sizePolicy().hasHeightForWidth())
        self.lineButton.setSizePolicy(sizePolicy)
        self.lineButton.setText("")
        self.lineButton.setObjectName("lineButton")
        self.closeButton = QtWidgets.QPushButton(self.topFream)
        self.closeButton.setGeometry(QtCore.QRect(1024, 0, 40, 40))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.closeButton.raise_()
        self.lineButton.raise_()
        self.midFream = QtWidgets.QFrame(self)
        self.midFream.setGeometry(QtCore.QRect(90, 50, 1074, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midFream.sizePolicy().hasHeightForWidth())
        self.midFream.setSizePolicy(sizePolicy)
        self.midFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.midFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.midFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.midFream.setObjectName("midFream")
        self.midlabel = QtWidgets.QLabel(self.midFream)
        self.midlabel.setGeometry(QtCore.QRect(50, 20, 181, 41))
        self.midlabel.setStyleSheet("font: 700 25pt \"微软雅黑\";")
        self.midlabel.setObjectName("midlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.midFream)
        self.lineEdit.setGeometry(QtCore.QRect(750, 30, 300, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"font: 15pt \"微软雅黑\";\n"
"border:2px;\n"
"border-color: rgb(0,24,102);\n"
"border-radius:20px;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.screenButton = QtWidgets.QPushButton(self.midFream)
        self.screenButton.setGeometry(QtCore.QRect(510, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenButton.sizePolicy().hasHeightForWidth())
        self.screenButton.setSizePolicy(sizePolicy)
        self.screenButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.screenButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"selection-background-color: rgb(231,244,255);")
        self.screenButton.setText("")
        self.screenButton.setObjectName("screenButton")
        self.label = QtWidgets.QLabel(self.midFream)
        self.label.setGeometry(QtCore.QRect(550, 40, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("\n"
"font: 15pt \"幼圆\";")
        self.label.setObjectName("label")
        self.midlabel.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.screenButton.raise_()
        self.mainFream = QtWidgets.QFrame(self)
        self.mainFream.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFream.sizePolicy().hasHeightForWidth())
        self.mainFream.setSizePolicy(sizePolicy)
        self.mainFream.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"\n"
"border-bottom-right-radius:10px;")
        self.mainFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream.setObjectName("mainFream")
        self.pushButton = QtWidgets.QPushButton(self.mainFream)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mainFream)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 40, 491, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.l1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l1.setStyleSheet("font: 20pt \"幼圆\";")
        self.l1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 0, 0, 1, 1)
        self.l3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l3.setStyleSheet("font: 20pt \"幼圆\";")
        self.l3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l3.setObjectName("l3")
        self.gridLayout.addWidget(self.l3, 2, 0, 1, 1)
        self.l4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l4.setStyleSheet("font: 20pt \"幼圆\";")
        self.l4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l4.setObjectName("l4")
        self.gridLayout.addWidget(self.l4, 3, 0, 1, 1)
        self.l5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l5.setStyleSheet("font: 20pt \"幼圆\";")
        self.l5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l5.setObjectName("l5")
        self.gridLayout.addWidget(self.l5, 4, 0, 1, 1)
        self.l2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l2.setStyleSheet("font: 20pt \"幼圆\";")
        self.l2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 1, 0, 1, 1)
        self.r1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.r1.setStyleSheet("font: 20pt \"幼圆\";")
        self.r1.setText("")
        self.r1.setObjectName("r1")
        self.gridLayout.addWidget(self.r1, 0, 1, 1, 1)
        self.r2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.r2.setStyleSheet("font: 20pt \"幼圆\";")
        self.r2.setText("")
        self.r2.setObjectName("r2")
        self.gridLayout.addWidget(self.r2, 1, 1, 1, 1)
        self.r3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.r3.setStyleSheet("font: 20pt \"幼圆\";")
        self.r3.setText("")
        self.r3.setObjectName("r3")
        self.gridLayout.addWidget(self.r3, 2, 1, 1, 1)
        self.r4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.r4.setStyleSheet("font: 20pt \"幼圆\";")
        self.r4.setText("")
        self.r4.setObjectName("r4")
        self.gridLayout.addWidget(self.r4, 3, 1, 1, 1)
        self.r5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.r5.setStyleSheet("font: 20pt \"幼圆\";")
        self.r5.setText("")
        self.r5.setObjectName("r5")
        self.gridLayout.addWidget(self.r5, 4, 1, 1, 1)


        '''最小化按钮'''
        icon1 = QIcon('img/icon-line.png')
        self.lineButton.setIcon(icon1)
        self.lineButton.clicked.connect(self.slot_mini_window)#

        '''关闭按钮'''
        icon2 = QIcon('img/icon-close.png')
        self.closeButton.setIcon(icon2)
        self.closeButton.clicked.connect(self.close)#

        '''头像，不变的。'''
        p1 = QPixmap('img/head.png')
        self.headLable.setPixmap(p1)

        '''左侧按钮，被点击之后的颜色变化'''
        self.leftButton1.clicked.connect(self.slot_leftButton1)
        self.leftButton2.clicked.connect(self.slot_leftButton2)
        self.leftButton3.clicked.connect(self.slot_leftButton3)
        self.leftButton4.clicked.connect(self.slot_leftButton4)

        self.mainFream2 = QtWidgets.QFrame(self)
        self.mainFream2.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFream2.sizePolicy().hasHeightForWidth())
        self.mainFream2.setSizePolicy(sizePolicy)
        self.mainFream2.setStyleSheet("background-color: rgb(233, 236, 239);\n"
                                     "\n"
                                     "border-bottom-right-radius:10px;")
        self.mainFream2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream2.setObjectName("mainFream2")
        self.pushButton = QtWidgets.QPushButton(self.mainFream2)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(self.mainFream2)
        self.tableView.setGeometry(QtCore.QRect(0, 10, 1074, 595))
        self.tableView.setObjectName("tableView")

        self.mainFream2.hide()
        self.mainFream.show()

        self.label.hide()
        self.lineEdit.hide()

        self.btOutput = QtWidgets.QPushButton(self.midFream)
        self.btOutput.setGeometry(QtCore.QRect(231, 20, 100, 40))
        self.btOutput.setStyleSheet("color: white;\n"
                                       "font: 15pt \"微软雅黑\";\n"
                                       "border-top-left-radius:0px;\n"
                                       "border-bottom-left-radius:0px;"
                                    "background-color:rgb(54,163,255);"
                                    "border-top-left-radius:10px;"
                                    "border-bottom-left-radius:10px;"
                                    "border-top-right-radius:10px;"
                                    "border-bottom-right-radius:10px;"
                                    "height:25px")
        self.btOutput.setObjectName("btOutput")

        self.btOutput.clicked.connect(self.output)

        my_delegate = item_delegate.my_item_delegate()
        self.tableView.setItemDelegate(my_delegate)
        self.tableView.setSortingEnabled(True)


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.leftButton2.setText(_translate("Form", "课表信息"))
        self.leftButton4.setText(_translate("Form", "成绩管理"))
        self.leftButton1.setText(_translate("Form", "个人信息"))
        self.leftButton3.setText(_translate("Form", "成绩信息"))
        self.midlabel.setText(_translate("Form", "欢迎使用"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.l1.setText(_translate("Form", "工号"))
        self.l3.setText(_translate("Form", "性别"))
        self.l4.setText(_translate("Form", "院系"))
        self.l5.setText(_translate("Form", "授课科目"))
        self.l2.setText(_translate("Form", "姓名"))
        self.btOutput.setText(_translate("Form", "输出报表"))


    def mousePressEvent(self, evt):
        '''可以自定义canMove_Flag = True需要满足的条件'''
        '''subWidgetMoveFlag子窗口被点击的瞬间，就被子窗口设置，值为子窗口是否允许拖动'''
        if ( True):
            # canMoveFlag被设置成Ture，标志着一个拖动过程的开始。mouseMoveEvent函数就是用这个去判断是否在拖动。
            self.canMoveFlag = True
            self.window_origin_x = self.x()
            self.window_origin_y = self.y()
            self.mouse_origin_x = QCursor.pos().x()
            self.mouse_origin_y =  QCursor.pos().y()

    def mouseMoveEvent(self, evt):
        '''通过一个if语句的判断，只能在canMoveFlag = True时才可以单击鼠标左键拖动这个widget'''
        if (self.canMoveFlag == True):
            self.mouse_des_x = QCursor.pos().x()
            self.mouse_des_y = QCursor.pos().y()
            self.window_des_x = self.window_origin_x + self.mouse_des_x - self.mouse_origin_x
            self.window_des_y = self.window_origin_y + self.mouse_des_y - self.mouse_origin_y
            self.move(self.window_des_x, self.window_des_y)

    def mouseReleaseEvent(self, evt):
        '''subWidgetMoveFlag在释放的瞬间，被设置成False，意味着一个拖动过程的结束'''
        self.canMoveFlag = False
        self.subWidgetMoveFlag = False

    def slot_mini_window(self):
        self.setWindowState(Qt.WindowState.WindowMinimized)

    def slot_leftButton1(self):
        self.leftButton1.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        query = QSqlQuery()
        query.exec("select id,name,sex,dept,course from teainfo where id='" + str(self.id) + "' ")
        print(query.lastError().text())
        query.next()
        '''查询结果'''
        self.r1.setText(str(query.value(0)))
        self.r2.setText(query.value(1))  # 姓名
        if query.value(2) == 0:
                self.r3.setText('男')  # 性别
        else:
                self.r3.setText('女')  # 性别
        self.r4.setText(query.value(3))  # 院系
        self.r5.setText(query.value(4))  #

        self.btOutput.hide()
        self.mainFream2.hide()
        self.mainFream.show()

    def slot_leftButton2(self):
        self.leftButton2.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
                                           "font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
                                           "font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        self.model = QSqlTableModel()
        self.model.setTable('courseinfo')
        self.tableView.setModel(self.model)
        self.model.setFilter("name='"+self.r2.text()+"'")
        self.model.select()

        self.tableView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)

        self.btOutput.show()
        self.mainFream.hide()
        self.mainFream2.show()

    def slot_leftButton3(self):
        self.leftButton3.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        self.model = QSqlTableModel()
        self.model.setTable('stuscore')
        self.tableView.setModel(self.model)
        self.model.setFilter("course='"+self.r5.text()+"'")
        self.model.select()
        self.tableView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)

        self.mainFream.hide()
        self.mainFream2.show()
        self.btOutput.show()

    def slot_leftButton4(self):
        self.leftButton4.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")
        self.tableView.setEditTriggers(QAbstractItemView.EditTrigger.DoubleClicked)
        self.model = QSqlTableModel()
        self.model.setTable('stuscore')
        self.tableView.setModel(self.model)
        self.model.setFilter("course='"+self.r5.text()+"'")
        self.model.select()

        self.mainFream.hide()
        self.btOutput.show()
        self.mainFream2.show()

    def output(self):
        workbook = xlwt.Workbook(encoding='ascii')
        # 创建新的sheet表
        worksheet = workbook.add_sheet("sheet")
        # 往表格写入内容,这里可以通过嵌套两层For循环历便表格内容后写入到excel文件中
        i = 0
        rowCount=self.model.rowCount()
        colCount=self.model.columnCount()
        while (i < rowCount):
            k=0
            while(k<colCount):
                tmp=self.model.data(self.model.index(i,k))
                worksheet.write(i, k, tmp)
                k=k+1
            i=i+1
        name_=str(datetime.now().year)+str(datetime.now().month)+str(datetime.now().day)
        name_=name_+str(datetime.now().hour)+str(datetime.now().minute)+str(datetime.now().second)
        workbook.save(name_+".xls")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = teaMain()
    sys.exit(app.exec())
