# Form implementation generated from reading ui file 'standardMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import datetime

import pymysql
from PyQt6 import QtCore, QtGui, QtWidgets, QtSql
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QCursor, QColor, QIcon, QPixmap
from PyQt6.QtSql import QSqlQuery, QSqlTableModel
from PyQt6.QtWidgets import QGraphicsDropShadowEffect




class stuMain(QtWidgets.QMainWindow):
    def __init__(self,id=205000):
        super(stuMain, self).__init__()
        self.id=id
        db = QtSql.QSqlDatabase.addDatabase('QMYSQL')
        q = "soft"
        db.setDatabaseName(q)
        db.setUserName('root')
        db.setPassword('root')
        db.setPort(3306)
        db.open()
        self.db=db
        self.setupUi()
        self.slot_leftButton1()
        self.show()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1174, 735)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        # 设置窗口无边框和阴影
        self.setWindowFlag(Qt.WindowType.FramelessWindowHint)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        effect = QGraphicsDropShadowEffect()
        effect.setOffset(6, 6)
        effect.setColor(QColor(0, 0, 0, 50))
        effect.setBlurRadius(10)
        self.setGraphicsEffect(effect)

        self.leftFream = QtWidgets.QFrame(self)
        self.leftFream.setGeometry(QtCore.QRect(10, 10, 80, 715))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFream.sizePolicy().hasHeightForWidth())
        self.leftFream.setSizePolicy(sizePolicy)
        self.leftFream.setStyleSheet("background-color: rgb(0, 24, 102);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.leftFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFream.setObjectName("leftFream")
        self.headLable = QtWidgets.QLabel(self.leftFream)
        self.headLable.setGeometry(QtCore.QRect(0, 40, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headLable.sizePolicy().hasHeightForWidth())
        self.headLable.setSizePolicy(sizePolicy)
        self.headLable.setText("")
        self.headLable.setObjectName("headLable")
        self.leftButton1 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton1.setGeometry(QtCore.QRect(0, 240, 80, 60))
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton1.setObjectName("leftButton1")
        self.leftButton2 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton2.setGeometry(QtCore.QRect(0, 300, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton2.sizePolicy().hasHeightForWidth())
        self.leftButton2.setSizePolicy(sizePolicy)
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton2.setObjectName("leftButton2")
        self.leftButton3 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton3.setGeometry(QtCore.QRect(0, 360, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton3.sizePolicy().hasHeightForWidth())
        self.leftButton3.setSizePolicy(sizePolicy)
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton3.setObjectName("leftButton3")
        self.leftButton4 = QtWidgets.QPushButton(self.leftFream)
        self.leftButton4.setGeometry(QtCore.QRect(0, 420, 80, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton4.sizePolicy().hasHeightForWidth())
        self.leftButton4.setSizePolicy(sizePolicy)
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.leftButton4.setObjectName("leftButton4")
        self.topFream = QtWidgets.QFrame(self)
        self.topFream.setGeometry(QtCore.QRect(90, 10, 1074, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFream.sizePolicy().hasHeightForWidth())
        self.topFream.setSizePolicy(sizePolicy)
        self.topFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:10px;\n"
"")
        self.topFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topFream.setObjectName("topFream")
        self.lineButton = QtWidgets.QPushButton(self.topFream)
        self.lineButton.setGeometry(QtCore.QRect(984, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineButton.sizePolicy().hasHeightForWidth())
        self.lineButton.setSizePolicy(sizePolicy)
        self.lineButton.setText("")
        self.lineButton.setObjectName("lineButton")
        self.closeButton = QtWidgets.QPushButton(self.topFream)
        self.closeButton.setGeometry(QtCore.QRect(1024, 0, 40, 40))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.closeButton.raise_()
        self.lineButton.raise_()
        self.midFream = QtWidgets.QFrame(self)
        self.midFream.setGeometry(QtCore.QRect(90, 50, 1074, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midFream.sizePolicy().hasHeightForWidth())
        self.midFream.setSizePolicy(sizePolicy)
        self.midFream.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.midFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.midFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.midFream.setObjectName("midFream")
        self.midlabel = QtWidgets.QLabel(self.midFream)
        self.midlabel.setGeometry(QtCore.QRect(50, 20, 181, 41))
        self.midlabel.setStyleSheet("font: 700 25pt \"微软雅黑\";")
        self.midlabel.setObjectName("midlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.midFream)
        self.lineEdit.setGeometry(QtCore.QRect(750, 30, 300, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"font: 15pt \"微软雅黑\";\n"
"border:2px;\n"
"border-color: rgb(0,24,102);\n"
"border-radius:20px;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.screenButton = QtWidgets.QPushButton(self.midFream)
        self.screenButton.setGeometry(QtCore.QRect(510, 40, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenButton.sizePolicy().hasHeightForWidth())
        self.screenButton.setSizePolicy(sizePolicy)
        self.screenButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.screenButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"selection-background-color: rgb(231,244,255);")
        self.screenButton.setText("")
        self.screenButton.setObjectName("screenButton")
        self.screenLabel = QtWidgets.QLabel(self.midFream)
        self.screenLabel.setGeometry(QtCore.QRect(550, 40, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenLabel.sizePolicy().hasHeightForWidth())
        self.screenLabel.setSizePolicy(sizePolicy)
        self.screenLabel.setStyleSheet("\n"
"font: 15pt \"幼圆\";")
        self.screenLabel.setText("")
        self.screenLabel.setObjectName("screenLabel")
        self.midlabel.raise_()
        self.lineEdit.raise_()
        self.screenLabel.raise_()
        self.screenButton.raise_()
        self.mainFream = QtWidgets.QFrame(self)
        self.mainFream.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFream.sizePolicy().hasHeightForWidth())
        self.mainFream.setSizePolicy(sizePolicy)
        self.mainFream.setStyleSheet("background-color: rgb(233, 236, 239);\n"
"\n"
"border-bottom-right-radius:10px;")
        self.mainFream.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream.setObjectName("mainFream")
        self.tableView = QtWidgets.QTableView(self.mainFream)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 950, 540))
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mainFream)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 110, 611, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("font: 15pt \"幼圆\";")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setStyleSheet("font: 15pt \"幼圆\";")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1)
        self.labelChange = QtWidgets.QLabel(self.mainFream)
        self.labelChange.setGeometry(QtCore.QRect(130, 40, 161, 81))
        self.labelChange.setStyleSheet("font: 20pt \"幼圆\";")
        self.labelChange.setObjectName("labelChange")
        self.lineEditChange = QtWidgets.QLineEdit(self.mainFream)
        self.lineEditChange.setGeometry(QtCore.QRect(310, 60, 331, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditChange.sizePolicy().hasHeightForWidth())
        self.lineEditChange.setSizePolicy(sizePolicy)
        self.lineEditChange.setStyleSheet("font: 15pt \"幼圆\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.lineEditChange.setMaxLength(15)
        self.lineEditChange.setObjectName("lineEditChange")
        self.enterPushButton = QtWidgets.QPushButton(self.mainFream)
        self.enterPushButton.setGeometry(QtCore.QRect(710, 60, 141, 41))
        self.enterPushButton.setStyleSheet("font: 15pt \"幼圆\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(1, 98, 255);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.enterPushButton.setObjectName("enterPushButton")


        '''最小化按钮'''
        icon1 = QIcon('icon-line.png')
        self.lineButton.setIcon(icon1)
        self.lineButton.clicked.connect(self.slot_mini_window)#

        '''关闭按钮'''
        icon2 = QIcon('icon-close.png')
        self.closeButton.setIcon(icon2)
        self.closeButton.clicked.connect(self.close)#

        '''头像，不变的。'''
        p1 = QPixmap('head.png')
        self.headLable.setPixmap(p1)

        '''左侧按钮，被点击之后的颜色变化'''
        self.leftButton1.clicked.connect(self.slot_leftButton1)
        self.leftButton2.clicked.connect(self.slot_leftButton2)
        self.leftButton3.clicked.connect(self.slot_leftButton3)
        self.leftButton4.clicked.connect(self.slot_leftButton4)

        '''转专业申请'''
        self.enterPushButton.clicked.connect(self.slot_change)


        '''第二个fream'''
        self.mainFream2 = QtWidgets.QFrame(self)
        self.mainFream2.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.mainFream2.sizePolicy().hasHeightForWidth())
        self.mainFream2.setSizePolicy(sizePolicy)
        self.mainFream2.setStyleSheet("background-color: rgb(233, 236, 239);\n"
                                     "\n"
                                     "border-bottom-right-radius:10px;")
        self.mainFream2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream2.setObjectName("mainFream2")
        self.tableView2 = QtWidgets.QTableView(self.mainFream2)
        self.tableView2.setGeometry(QtCore.QRect(0, 0, 950, 540))
        self.tableView2.setObjectName("tableView2")
        self.mainFream2.hide()

        '''第三个fream'''
        self.mainFream3 = QtWidgets.QFrame(self)
        self.mainFream3.setGeometry(QtCore.QRect(90, 130, 1074, 595))
        sizePolicy2 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.mainFream3.sizePolicy().hasHeightForWidth())
        self.mainFream3.setSizePolicy(sizePolicy)
        self.mainFream3.setStyleSheet("background-color: rgb(233, 236, 239);\n"
                                      "\n"
                                      "border-bottom-right-radius:10px;")
        self.mainFream3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFream3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFream3.setObjectName("mainFream3")
        self.tableView3 = QtWidgets.QTableView(self.mainFream3)
        self.tableView3.setGeometry(QtCore.QRect(0, 0, 950, 540))
        self.tableView3.setObjectName("tableView3")
        self.mainFream3.hide()


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.leftButton1.setText(_translate("Form", "个人信息"))
        self.leftButton2.setText(_translate("Form", "课表信息"))
        self.leftButton3.setText(_translate("Form", "成绩信息"))
        self.leftButton4.setText(_translate("Form", "转专业"))
        self.midlabel.setText(_translate("Form", "欢迎使用"))
        self.label_8.setText(_translate("Form", "专业"))
        self.label_3.setText(_translate("Form", "姓名"))
        self.label_10.setText(_translate("Form", "班级"))
        self.label_4.setWhatsThis(_translate("Form", "<html><head/><body><p>font: 20pt &quot;幼圆&quot;;</p></body></html>"))
        self.label_4.setText(_translate("Form", "院系"))
        self.label_2.setText(_translate("Form", "学号"))
        self.label_9.setText(_translate("Form", "性别"))
        self.labelChange.setText(_translate("Form", "申请专业："))
        self.enterPushButton.setText(_translate("Form", "确认"))

    def mousePressEvent(self, evt):
        '''可以自定义canMove_Flag = True需要满足的条件'''
        '''subWidgetMoveFlag子窗口被点击的瞬间，就被子窗口设置，值为子窗口是否允许拖动'''
        if ( True):
            # canMoveFlag被设置成Ture，标志着一个拖动过程的开始。mouseMoveEvent函数就是用这个去判断是否在拖动。
            self.canMoveFlag = True
            self.window_origin_x = self.x()
            self.window_origin_y = self.y()
            self.mouse_origin_x = QCursor.pos().x()
            self.mouse_origin_y =  QCursor.pos().y()

    def mouseMoveEvent(self, evt):
        '''通过一个if语句的判断，只能在canMoveFlag = True时才可以单击鼠标左键拖动这个widget'''
        if (self.canMoveFlag == True):
            self.mouse_des_x = QCursor.pos().x()
            self.mouse_des_y = QCursor.pos().y()
            self.window_des_x = self.window_origin_x + self.mouse_des_x - self.mouse_origin_x
            self.window_des_y = self.window_origin_y + self.mouse_des_y - self.mouse_origin_y
            self.move(self.window_des_x, self.window_des_y)

    def mouseReleaseEvent(self, evt):
        '''subWidgetMoveFlag在释放的瞬间，被设置成False，意味着一个拖动过程的结束'''
        self.canMoveFlag = False
        self.subWidgetMoveFlag = False

    def slot_mini_window(self):
        self.setWindowState(Qt.WindowState.WindowMinimized)



    def slot_leftButton1(self):
        self.leftButton1.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        # self.leftButton1.setText(("Form", "个人信息"))
        # self.leftButton2.setText(("Form", "课表信息"))
        # self.leftButton3.setText(("Form", "成绩信息"))
        # self.leftButton4.setText(("Form", "转专业"))
        # self.midlabel.setText(("Form", "欢迎使用"))
        self.label_8.show()
        self.label_3.show()
        self.label_10.show()

        self.label_4.show()
        self.label_2.show()
        self.label_9.show()
        self.labelChange.hide()
        self.enterPushButton.hide()
        self.lineEditChange.hide()
        self.lineEdit.hide()
        self.tableView.hide()
        self.mainFream.show()
        self.mainFream2.hide()
        self.label_5.show()
        self.label_6.show()  # 姓名
        self.label_7.show()  # 院系
        self.label_11.show()  # 专业
        self.label_12.show()  # 性别
        self.label_13.show()  # 班级

        self.set_text()

    def set_text(self):
        query=QSqlQuery()
        query.exec("select id,name,dept,major,sex,class from stuinfo where id='" +str(self.id)+"' ")
        print(query.lastError().text())
        query.next()
        '''查询结果'''
        self.label_5.setText(str(query.value(0)))
        self.label_6.setText(query.value(1))#姓名
        self.label_7.setText(query.value(2))#院系
        self.label_11.setText(query.value(3))#专业
        if query.value(4)==0:
            self.label_12.setText('男')#性别
        else:
            self.label_12.setText('女')  # 性别
        self.label_13.setText(query.value(5))#班级





    def slot_leftButton2(self):
        self.leftButton2.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
                                           "font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
                                           "font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_11.hide()
        self.label_12.hide()
        self.label_13.hide()
        self.label_8.hide()
        self.label_3.hide()
        self.label_10.hide()
        self.label_4.hide()
        self.label_2.hide()
        self.label_9.hide()
        self.labelChange.hide()
        self.enterPushButton.hide()
        self.lineEditChange.hide()
        self.lineEdit.hide()
        self.tableView.hide()

        class_=self.label_13.text()
        self.model=QSqlTableModel()
        self.tableView2.setModel(self.model)
        self.model.setTable('courseinfo')
        self.model.setFilter("class='"+class_+"' ")
        self.tableView2.show()
        self.model.select()

        self.mainFream.hide()
        self.mainFream3.hide()
        self.mainFream2.show()


    def slot_leftButton3(self):
        self.leftButton3.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton4.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")

        # self.label_5.hide()
        # self.label_6.hide()
        # self.label_7.hide()
        # self.label_11.hide()
        # self.label_12.hide()
        # self.label_13.hide()
        # self.label_8.hide()
        # self.label_3.hide()
        # self.label_10.hide()
        # self.label_4.hide()
        # self.label_2.hide()
        # self.label_9.hide()
        # self.labelChange.hide()
        # self.enterPushButton.hide()
        # self.lineEditChange.hide()
        # self.lineEdit.hide()
        # self.tableView.hide()

        self.model = QSqlTableModel()
        self.tableView3.setModel(self.model)
        self.model.setTable('stuscore')
        self.model.setFilter("id=%d "%self.id)
        self.tableView3.show()
        self.model.select()

        self.mainFream.hide()
        self.mainFream2.hide()
        self.mainFream3.show()

    def slot_leftButton4(self):
        self.leftButton4.setStyleSheet(
                    "background-color:rgb(28,110,255);color:rgb(255,255,255);font: 12pt \"微软雅黑\";")
        self.leftButton2.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton1.setStyleSheet("color: rgb(233,236,239);\n"
"font: 12pt \"微软雅黑\";")
        self.leftButton3.setStyleSheet("color: rgb(233,236,239);\n"
                                       "font: 12pt \"微软雅黑\";")
        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_11.hide()
        self.label_12.hide()
        self.label_13.hide()
        self.label_8.hide()
        self.label_3.hide()
        self.label_10.hide()
        self.label_4.hide()
        self.label_2.hide()
        self.label_9.hide()
        self.labelChange.hide()
        self.lineEditChange.hide()
        self.lineEdit.hide()
        self.tableView.hide()
        self.mainFream2.hide()
        self.mainFream3.hide()
        self.mainFream.show()
        self.labelChange.show()
        self.lineEditChange.show()
        self.enterPushButton.show()

    def slot_change(self):
        res=self.lineEditChange.text()
        self.lineEditChange.setText("已提交")
        self.lineEditChange.repaint()
        self.enterPushButton.setDisabled(True)
        dt = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        query=QSqlQuery()
        query.exec("insert into applys(name,date,appcontent,id) values('" + self.label_6.text() + "','"+dt+"', '转专业申请"+res+"' , '"+str(self.id)+"') ")
        self.db.commit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = stuMain()
    sys.exit(app.exec())
